# Generated by Django 5.0.6 on 2024-05-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Predict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gugun', models.CharField(max_length=200)),
                ('road_name', models.CharField(max_length=200)),
                ('road_number', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
