# Generated by Django 5.0.6 on 2024-05-27 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='predict',
            table='predict',
        ),
    ]
